# Generated by Django 6.0.4 on 2026-05-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (EN)')),
                ('name_zh_hant', models.CharField(blank=True, max_length=200, verbose_name='Name (ZH-Hant)')),
                ('name_zh_hans', models.CharField(blank=True, max_length=200, verbose_name='Name (ZH-Hans)')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Name (EN)')),
                ('name_zh_hant', models.CharField(blank=True, max_length=300, verbose_name='Name (ZH-Hant)')),
                ('name_zh_hans', models.CharField(blank=True, max_length=300, verbose_name='Name (ZH-Hans)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('description_zh_hant', models.TextField(blank=True, verbose_name='Description (ZH-Hant)')),
                ('description_zh_hans', models.TextField(blank=True, verbose_name='Description (ZH-Hans)')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (USD)')),
                ('pv', models.IntegerField(default=0, help_text='Product Value points for MLM calculations', verbose_name='PV')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
